<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="Mayur" failures="1" tests="2" name="Default test(failed)(failed)" time="12.079" errors="0" timestamp="2023-01-08T15:47:31 IST">
  <testcase classname="ProgramMethod.FailedTestCase" name="Test3" time="0.106"/>
  <testcase classname="ProgramMethod.FailedTestCase" name="Test4" time="0.06">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at ProgramMethod.FailedTestCase.Test4(FailedTestCase.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test4 -->
  <testcase classname="ProgramMethod.FailedTestCase" name="Test1" time="0.0">
    <ignored/>
  </testcase> <!-- Test1 -->
  <testcase classname="ProgramMethod.FailedTestCase" name="Test2" time="0.0">
    <ignored/>
  </testcase> <!-- Test2 -->
  <testcase classname="ProgramMethod.FailedTestCase" name="Test5" time="0.0">
    <ignored/>
  </testcase> <!-- Test5 -->
</testsuite> <!-- Default test(failed)(failed) -->
